data:
  data_dir: ../data
  log_dir: ../logs
  src_dir: ./
  train_with_noise: True
  add_self_loops: True
  virtual_node: True
  only_one_tau: True
  splits:
    train: 0.7
    valid: 0.15
    test: 0.15
  pos2neg: 0.16
  random_state: 1
  mix_samples: False
  mix_and_check: False
  pred_pt: False
  visz: False
  filter_soft_mu: False

  conditions:
    1-mu_hit_station: '==1'
    2-n_mu_hit: '>= 3'

  node_feature_names:
    - mu_hit_ring
    - mu_hit_quality
    - mu_hit_bend
    - mu_hit_sim_phi
    - mu_hit_sim_theta
    - mu_hit_sim_eta
    - mu_hit_sim_r
    - mu_hit_sim_z
  edge_feature_names:
    - mu_hit_sim_phi
    - mu_hit_sim_theta
    - mu_hit_sim_eta
    - mu_hit_sim_r
    - mu_hit_sim_z

model:
  focal_loss: True
  focal_alpha: 0.5
  focal_gamma: 3
  att_sup: False
  att_unsup: False
  epochs: 500
  batch_size: 256
  lr: 4e-4
  n_layers: 16
  heads: 3
  out_channels: 128
  model_name: DeepGCN
  readout: rnn
  dropout: True
  scheduler: False
  att_sup_min_score: 0.2
  kl_beta: 0.1
  rmse_beta: 0.025
  norm_type: BN
  topk_pooling: False
  resume: False
  only_eval: False

eval:
  test_interval: 5
  auroc_max_fpr: 0.001
