data:
  data_dir: ../data
  log_dir: ../logs
  src_dir: ./
  train_with_noise: True
  add_self_loops: True
  virtual_node: True
  only_one_tau: True
  splits:
    train: 0.8
    valid: 0.2
    test: 0.0
  pos2neg: 0.16
  random_state: 1
  mix_samples: False
  mix_and_check: False
  pred_pt: False
  visz: False
  filter_soft_mu: False
  da_test: True
  normalize: False
  one_hot: False

  conditions:
    1-mu_hit_station: '==1'
    2-n_mu_hit: '>= 3'

  node_feature_names:
    - mu_hit_ring
    - mu_hit_quality
    - mu_hit_bend
    - mu_hit_sim_phi
    - mu_hit_sim_theta
    - mu_hit_sim_eta
    - mu_hit_sim_r
    - mu_hit_sim_z
  edge_feature_names:
    - mu_hit_sim_phi
    - mu_hit_sim_theta
    - mu_hit_sim_eta
    - mu_hit_sim_r
    - mu_hit_sim_z

model:
  resume: DeepGCN-05_25_2021-22_03_39-station1_16layers_05-30focalloss_16pos2neg_fcdropout_rnn_500epoch_learnagg_moredropout
  only_eval: True
  n_layers: 16
  out_channels: 128
  model_name: DeepGCN
  dropout_p: 0.5
  norm_type: batch
  readout: lstm
  share: False
  heads: 3
  epochs: 500
  batch_size: 256
  lr: 4e-4
  focal_loss: True
  focal_alpha: 0.5
  focal_gamma: 3
  deepgcn_aggr: softmax
  att_sup_min_score: 0.2
  kl_beta: 0.1
  rmse_beta: 0.025
  scheduler: False
  att_sup: False
  att_unsup: False
  topk_pooling: False

eval:
  test_interval: 5
  auroc_max_fpr: 0.001
